#' SCurve
#'
#' @description
#' This data provides the shut-down assumptions by fuel and technology at the state level
#'
#' @details
#' Generated by running `inst/extdata/GCAM/GCAM8p8/Assumption.R`. Follow
#' package plutus to gather the assumptions.
#'
#' @source
#' GCAM assumptions used in GCAM-USA 8.8; see inst/extdata/GCAM/GCAM8p8/Assumption.R
#'
#' @examples
#' data(SCurve)
"SCurve"


#' hydro_cf
#'
#' @description
#' This data provides a state-level annual capacity factor of hydro power
#'
#' @format
#' A data frame with `49` rows and `3` variables:
#'
#' @source
#' Hall et al., 2003. Table 8, exported as GODEEP/Assumptions/hydro_CF_USA.csv
#' state level monthly capacity factor
#'
#' @examples
#' data(hydro_cf)
"hydro_cf"


#' rooftop_hist_gen
#'
#' @description
#' State-level historic rooftop (small-scale) solar PV generation for 2024,
#' in EJ. Used by GCAM_EJ() to correct rooftop PV's first modeled-period
#' additions: GCAM has no rooftop PV data before the model's first future
#' year, so without this correction the entire pre-existing historic
#' rooftop fleet is counted as newly built capacity in that period.
#'
#' @format
#' A data frame with `51` rows (50 states + DC) and `4` variables:
#' `region`, `value` (EJ), `fuel`, `year`.
#'
#' @source
#' EIA small-scale (distributed) solar PV monthly generation, summed to
#' annual 2024 totals per state; see inst/extdata/rooftop_hist_gen_2024.csv
#' (originally "thousand megawatthours", i.e. GWh, converted to EJ via
#' CONV_GWH_EJ).
#'
#' @examples
#' data(rooftop_hist_gen)
"rooftop_hist_gen"


#' OM_cost
#'
#' @description
#' This data technology level OM fixed and variable cost information
#'
#' @details
#' Generated by running `inst/extdata/GCAM/GCAM8p8/Assumption.R`.
#'
#' @source
#' GCAM data, GCAM-USA 8.8; see inst/extdata/GCAM/GCAM8p8/Assumption.R
#'
#' @examples
#' data(OM_cost)
"OM_cost"


#' mapUS52Compact
#'
#' @description
#' This data presents the spatial information of USA states
#'
#' @source
#' https://github.com/JGCRI/rmap/tree/main/data
#'
#' @examples
#' data(mapUS52Compact[, 1:6])
"mapUS52Compact"



#' colors
#'
#' @description
#' specify the fill color by job type fr plot functions
"colors"


#' theme0
#'
#' @description
#' specify plot theme0
"theme0"

#' theme1
#'
#' @description
#' specify plot theme1
"theme1"

#' theme_leg
#'
#' @description
#' specify plot theme_leg
"theme_leg"

#' Conversion factor from exajoules to kilowatt-hours
#'
#' A numeric conversion factor used to convert energy values from EJ to kWh.
#'
#' @format A numeric value.
#' @keywords datasets
"CONV_EJ_KWH"

#' Conversion factor from gigawatt-hours to exajoules
#'
#' A numeric conversion factor used to convert energy values from GWh to EJ.
#'
#' @format A numeric value.
#' @keywords datasets
"CONV_GWH_EJ"

#' Raw JEDI employment factors
#'
#' Raw employment factor data used in GCAM-USA jobs calculations.
#'
#' @format A data frame.
#' @keywords datasets
"EF.JEDI.RAW"

#' Processed JEDI employment factors
#'
#' Processed employment factor data used in GCAM-USA jobs calculations.
#'
#' @format A data frame.
#' @keywords datasets
"EF.JEDI"

#' GCAM future start year
#'
#' Starting year used for future GCAM model periods.
#'
#' @section Deprecated:
#' No longer used internally - year sequences are now derived at runtime
#' from actual query data (see `gcam_future_years()`). Retained only for
#' backward compatibility with code that may reference it directly, and
#' reflects the GCAM-USA v7.1 assumption (2020); not guaranteed to match
#' the base year of any GCAM-USA version you are actually running.
#'
#' @format A numeric value.
#' @keywords datasets
"GCAM_futr_start"

#' GCAM future end year
#'
#' Ending year used for future GCAM model periods.
#'
#' @section Deprecated:
#' No longer used internally - year sequences are now derived at runtime
#' from actual query data (see `gcam_future_years()`). Retained only for
#' backward compatibility with code that may reference it directly, and
#' reflects the GCAM-USA v7.1 assumption (2100); not guaranteed to match
#' the model end year of any GCAM-USA version you are actually running.
#'
#' @format A numeric value.
#' @keywords datasets
"GCAM_futr_end"

#' GCAM model time step
#'
#' Time step used between GCAM model years.
#'
#' @format A numeric value.
#' @keywords datasets
"GCAM_model_step"

#' Conversion factor from gigawatts to megawatts
#'
#' A numeric conversion factor used to convert GW to MW.
#'
#' @format A numeric value.
#' @keywords datasets
"convGW_MW"

#' Conversion factor from megawatts to kilowatts
#'
#' A numeric conversion factor used to convert MW to kW.
#'
#' @format A numeric value.
#' @keywords datasets
"convMW_kW"

#' GCAM-USA states
#'
#' State-level identifiers used by GCAM-USA jobs calculations.
#'
#' @format A character vector or data frame.
#' @keywords datasets
"gcamusa.STATES"

#' Geographic capacity factor data
#'
#' Geographic capacity factor data used in GCAM-USA jobs calculations.
#'
#' @format A data frame.
#' @keywords datasets
"geo_cf"

#' Nuclear capacity factor
#'
#' Fixed nuclear capacity factor used in GCAM-USA jobs calculations. Nuclear
#' is not covered by the 'GCAM_USA elec cap-fac by cooling tech' query (like
#' geo_cf and hydro_cf, it is handled as a separate fuel in GCAM_EJ()
#' rather than looked up from that query).
#'
#' @format A numeric value.
#' @keywords datasets
"nuc_cf"

#' Example trial data
#'
#' Example data used for testing or demonstration.
#'
#' @format A data frame.
#' @keywords datasets
"trial_data"

#' GCAM year mapping data
#'
#' Mapping between GCAM model years and related time periods.
#'
#' @section Deprecated:
#' Not used anywhere internally (had no consumers even before other
#' GCAM-USA-version-dependent constants were deprecated). Reflects the
#' GCAM-USA v7.1 assumption (2015 calibration year, future years from
#' 2020 by 5); not guaranteed to match any GCAM-USA version you are
#' actually running. Retained only for backward compatibility.
#'
#' @format A data frame.
#' @keywords datasets
"years_mapping"
